[tox]
envlist =
    py313
    py314
    py315
isolated_build = True
requires =
    tox-uv>=1.28

[testenv]
deps =
    # parameterized
    pytest>=7.4.4
    pytest-cov>=4.1.0
    hypothesis
commands =
    py.test --cov-report term-missing --cov=dedlin
