name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - name: Install Poetry
        run: |
          pip install pipenv

      - name: Install Dependencies
        run: pipenv install --dev --skip-lock

      - name: Run Makefile
        run: make check
