name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          pip install pipenv

      - name: Install Dependencies
        run: pipenv install --dev --skip-lock

      - name: Run Makefile
        run: make check
